### ISSUE TITLE
Hoofdlettergevoeligheid UCI opties

### ISSUE THREAD

**Issue by djdekker** [kervinck/floyd#1]
Dag Marcel,
Als ik de code in uci.c goed begrijp, zijn de namen van de UCI-opties in Floyd 0.9 (Hash, Ponder, Clear Hash) hoofdlettergevoelig. Volgens het UCI-protocol zouden ze echter hoofdletterONgevoelig moeten zijn. Dit geeft problemen met de python-chess library, die alle UCI-opties eerst omzet naar kleine letters voordat hij ze aan de engine doorgeeft.
Groet,
DJ

**Comment by kervinck** [comment]
Oei, dat is dan inderdaad een probleem. Dat kan ik wel oplossen, maar ik wilde net deze ochtend v0.9 uitbrengen. Ik wacht alleen nog op de compilatie voor w64. Daar gaat het niet meer inkomen.

Is het niet makkelijker dat python-chess van de case afblijft?
Anyway, een snelle workaround voor pico-chess is om floyd om te hacken en alles als kleine-letters te laten zien.

Bedankt voor het melden, ik zal morgen kijken wat een definitieve oplossing moet worden en dan beslissen of ik een 0.9.1 maak voor rpi.
Marcel

**Comment by djdekker** [comment]
Hoi Marcel,

Ik had al zo’n idee dat ik snel moest zijn omdat je op het punt stond 0.9 uit te brengen! Ik had het probleem gisteravond ontdekt. Nét te laat dus. :D

Natuurlijk heb je gelijk en moet python-chess gewoon van die optienamen afblijven (andere engines lopen hier ook tegenaan), maar de UCI specs laten het toe. Ik denk dat ik voorlopig de optienamen in de Floyd source in kleine letters omzet.

Bedankt voor je snelle reactie.
Groet,
DJ

> Op 20 aug. 2016, om 10:19 heeft Marcel van Kervinck notifications@github.com het volgende geschreven:
> 
> Oei, dat is dan inderdaad een probleem. Dat kan ik wel oplossen, maar ik wilde net deze ochtend v0.9 uitbrengen. Ik wacht alleen nog op de compilatie voor w64. Daar gaat het niet meer inkomen.
> 
> Is het niet makkelijker dat python-chess van de case afblijft?
> Anyway, een snelle workaround voor pico-chess is om floyd om te hacken en alles als kleine-letters te laten zien.
> 
> Bedankt voor het melden, ik zal morgen kijken wat een definitieve oplossing moet worden en dan beslissen of ik een 0.9.1 maak voor rpi.
> Marcel
>

**Comment by kervinck** [comment]
Het is misschien niet makkelijk definitief op te lossen omdat ik de matching in de C library doe en die heeft geen case-ignoring variant van sscanf. (De mixed-case output van het “uci” commando wil ik daarbij wel behouden.)

Misschien werkt zoiets als dit voor je?

```
            else if (scan("setoption")) {
                    for (int i=0; line[i]; i++) line[i] = tolower(line[i]);
                    if (scanValue("name hash value %ld", &newOptions.Hash)) pass;
                    else if (scan("name ponder value true")) pass;
                    else if (scan("name ponder value false")) pass; // just ignore it
                    else if (scan("name clear hash")) newOptions.ClearHash = !oldOptions.ClearHash;
            }
```

Even een ander topic: doet pico-chess ook fisher random / chess960? Ik twijfel nog of ik dat ga toevoegen, en voor zover ik weet ben je daar min of meer verplicht af te wijken van wat de UCI spec zegt over castling vanwege Arena. Ik weet niet of ik dat goed begrijp.

Marcel

**Comment by djdekker** [comment]
Dank je wel, dat ga ik proberen.

PicoChess ondersteunt dankzij de python-chess lib inderdaad ook chess960! Het werkt nu al goed, maar er zijn nog maar heel weinig open source engines die dit kunnen (Stockfish bijv. wel). Vind ik erg leuk om te spelen. Geweldig mooi als Floyd op een dag ook chess960 zou ondersteunen!

**Comment by kervinck** [comment]
Voor zover ik kan zien is de impact van dit issue redelijk beperkt. Dat is ook wel logisch want het zit er al sinds het eerste begin zo in en nu pas gevonden. "Clear hash" doet niks en het is niet mogelijk om de hash size van 256MB te veranderen onder Pico Chess. De ponder optie wordt sowieso beleefd genegeerd want de echte trigger komt met het "go" commando. Dus dat zo moeten werken. Verder heeft floyd geen uci opties :-)

Voor de Raspberry Pi Model A is er wel een issue want die hebben maar 256MB. Laten we zeggen: als PicoChess niet kan werken met een on-gemodificeerde v0.9 dan breng ik met alle liefde een v0.9.1 punt-release uit. En anders wacht ik tot ik het mee kan nemen in de volgende echte release. Is dat ok?

**Comment by kervinck** [comment]
Correctie: de default is 128MB hash.

**Comment by kervinck** [comment]
The above solution is not nice if the "value" part is a string. This can happen in the future if we add support for Syzygy for example.

Therefore an alternative solution that doesn't add to the line count:

```
            else if (scan("setoption")) {
                    if (scanValue("name %*[Hh]ash value %ld", &newOptions.Hash)) pass;
                    else if (scan("name %*[Pp]onder value true")) pass;
                    else if (scan("name %*[Pp]onder value false")) pass; // just ignore it
                    else if (scan("name %*[Cc]lear %*[Hh]ash")) newOptions.ClearHash = !oldOptions.ClearHash;
            }
```

(Technically things like "HASH" end "HaSh" still get rejected but are allowed by the UCI standard.)

**Comment by kervinck** [comment]
Should be fixed as above in branch `dev' with commit
https://github.com/kervinck/floyd/commit/a7c0813e5b5122222e811bc6f5cab1a470de9c45
Will become released with the first next full release, unless this issue becomes critical for PicoChess or other applications.
